### ISSUE TITLE
Problems on plotting st_gap

### ISSUE THREAD

**Issue by lycheehoo** [eimrek/tb-mean-field-hubbard#8]
Dear developer, I just transform example.ipynb into example.py and ran it for clars_goblet.xyz, everything went successfully except plotting △Est variation using relevant codes below, it seemed that these codes did not work:

```
# In[ ]:


# Reproducing Extended Data Fig. 1 from
# Mishra 2020 "Topological frustration induces unconventional magnetism in a nanographene"

u_t_ratios = np.arange(0.5, 1.6, 0.1)

singlet_energies = []
triplet_energies = []

for ut_ratio in u_t_ratios:
    
    u = ut_ratio * t
    
    singlet_mfh_model.run_mfh(u)
    singlet_energies.append(singlet_mfh_model.energy)
    
    triplet_mfh_model.run_mfh(u)
    triplet_energies.append(triplet_mfh_model.energy)
    
singlet_energies = np.array(singlet_energies)
triplet_energies = np.array(triplet_energies)

st_gap = triplet_energies - singlet_energies


# In[ ]:


plt.plot(u_t_ratios, st_gap*1000, 'o-')
plt.ylabel("triplet - singlet [meV]")
plt.xlabel("U/t")
plt.show()

```

Besides, I found an abnormal image as shown. Is this image correponding to the outcome from above codes?
![Figure_1](https://github.com/eimrek/tb-mean-field-hubbard/assets/117914902/1e53595d-e854-4e2a-83d4-8350b83466f8)

**Comment by eimrek** [comment]
Hi @lycheehoo, could you attach or copy-paste the whole `example.py` file you made?

**Comment by lycheehoo** [comment]
The file is as below. 
[example.zip](https://github.com/eimrek/tb-mean-field-hubbard/files/11642226/example.zip)

**Comment by eimrek** [comment]
Thanks for the report @lycheehoo 

Indeed, there was an issue that didn't show up in the jupyter notebook. Namely, the `mfh_model.pp.plot_orb_squared_map(evec)` line was drawing into the matplotlib buffer but did not show it. This caused it and the next plot to be merged.

This should be fixed now in 2.2.0 (with 98c4979) The example.ipynb is modified slightly, so you need to re-convert it to a python script.

**Comment by lycheehoo** [comment]
Thanks eimrek, it runs smoothly. Your excellent job really makes it easier for me to get relevant molecular messages. But for the .xyz file, I am confused of the numbers in the 5th column(as sighed in red below), what is the meaning of them? And how can I prepare this kind of file using specific softwares like materials studio? Besides, can these codes be applied in the situation that a sp2 carbon system with doped N or B atoms?

![image](https://github.com/eimrek/tb-mean-field-hubbard/assets/117914902/79f5f962-5333-4633-9393-44b196246515)

**Comment by eimrek** [comment]
Hi @lycheehoo, that's the spin guess (1 = up, 2 = down). It's also plotted at the start of the example script. You can use ase to visualize and modify it, mentioned in the example script as well.

```
# Geometry
geom = ase.io.read("geom/clars_goblet.xyz")

# Use the following to scale all CC bonds to a specific length
#tbmfh.utils.scale_to_cc_bond_length(geom, cc_bond=1.42)

# Spin guess is set in atom tags (1 - up, 2 - down)
# one option is to use the following (edit->modify)
# to visualize the spin guess use (view->colors->by tag)
geom.edit()
```

**Comment by eimrek** [comment]
Regarding N or B doped, you could override some sites to have different on-site energy:

https://github.com/eimrek/tb-mean-field-hubbard/blob/master/tb_mean_field_hubbard/mfh.py#L163

or hoppings:

https://github.com/eimrek/tb-mean-field-hubbard/blob/master/tb_mean_field_hubbard/mfh.py#L141

This could be used to represent heteroatoms, and has been done in literature, although as i haven't done it myself, i don't know the exact details.

Hope this helps! Good luck!

**Comment by lycheehoo** [comment]
OK, I got it. Hope you everything goes well!

**Comment by lycheehoo** [comment]
Hello eimrek, I want to know if this model can solve periodic systems like graphene nanoribbons? Or just build a slab model as an input .xyz file?

**Comment by eimrek** [comment]
Hi @lycheehoo. Unfortunately, currenlty there is no support for periodic systems.
